defmodule MonkeyClawWeb.Endpoint do
  @moduledoc """
  Phoenix endpoint for MonkeyClaw.

  Handles HTTP/HTTPS transport, static asset serving, LiveView
  WebSocket connections, session management, and the plug pipeline.
  In production, all connections are gated by mTLS at the transport
  layer — only requests with a valid client certificate reach any
  route.
  """
  use Phoenix.Endpoint, otp_app: :monkey_claw

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_monkey_claw_key",
    signing_salt:
      Application.compile_env!(:monkey_claw, [MonkeyClawWeb.Endpoint, :session_signing_salt]),
    same_site: "Lax",
    secure: true
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [:peer_data, session: @session_options]],
    longpoll: [connect_info: [:peer_data, session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :monkey_claw,
    gzip: not code_reloading?,
    only: MonkeyClawWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :monkey_claw
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    length: 1_000_000,
    body_reader: {MonkeyClawWeb.Plugs.CacheBodyReader, :read_body, []}

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug MonkeyClawWeb.Router
end
