import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :monkey_claw, MonkeyClawWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  # Session signing salt is a key-derivation namespace, not a secret.
  # It prevents cookie signatures from one application being valid for
  # another. The actual security comes from secret_key_base. This must
  # be a compile-time constant because @session_options is a module
  # attribute expanded at compile time by plug Plug.Session.
  session_signing_salt: "mC_prd_sess_8kLm"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :monkey_claw, MonkeyClawWeb.Endpoint,
  force_ssl: [
    hsts: true,
    expires: 31_536_000
  ]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
